# Лабораторная работа №1
## Выполнил студент группы бПМ2 Серебряков Егор Николаевич
### Задание №1
вариант 15 (вариант это же номер в списке группы?)

In [49]:
print('Hello, world!')

Hello, world!


### Задание №2
генератор случайных матриц

In [17]:
import numpy as np

def mat_gen():
    while True:
        print('import height or blank')
        m = input()
        if m.isspace() or m =='':
            m = 50

        m = int(m)
        if m < 0:
            print('import natural value!')
        else:
            break

    while True:
        print('import lenght or blank')
        n = input()
        if n.isspace() or n =='':
            n = 50

        n = int(n)
        if n < 0:
            print('import natural value!')
        else:
            break

    while True:
        print('import min value or blank')
        min_limit = input()
        if min_limit.isspace() or min_limit =='':
            min_limit = -250

        min_limit = int(min_limit)

        print('import max value or blank')
        max_limit = input()
        if max_limit.isspace() or max_limit =='':
            max_limit = 1000 + 15

        max_limit = int(max_limit)
        if max_limit - min_limit < 0:
            print('the segment is degenerate')
        else:
            break 

    return np.random.randint(min_limit, max_limit+1, (m, n))

showcase_mat = mat_gen()
print(showcase_mat)

import height or blank

import lenght or blank

import min value or blank

import max value or blank

[[ -32  585  256 ...  857  384  -44]
 [ 479 1003   18 ...  694  121  464]
 [ 987  319   49 ...   44  618  457]
 ...
 [-166  381  134 ...  513  998  855]
 [  23  863  919 ... -108  432  407]
 [ 209  367    1 ...  -39  517 -228]]


In [8]:
#сортировка выбором

mat = mat_gen()
print('before sorting')
print(mat)

def vblbor(mat):
    for i in range(np.ma.size(mat, 0)):
        for j in range(np.ma.size(mat, 1)):
            mat[i, [j, np.argmin((mat[i, j:])) + j]] = mat[i, [np.argmin((mat[i, j:])) + j, j]]

            
print('after sorting')
vblbor(mat)
print(mat)

import height or blank

import lenght or blank

import min value or blank

import max value or blank

before sorting
[[ 132  578  834  730   43  -68   61  602   98  134   86  801    5  284
   995 -166 -231  890  107  230]
 [  84  579  498  592  -75  169  481  447 -191 -205  607  241 -135  380
  -142  739  869 -110  -64 -202]
 [ 191  -44  -43   12  841  179  -38  712  197 -241  310  841  662  100
   852  535  879 1011 1003  971]
 [ 263 -112  -93  961  209  679    2  888  489  660   30  133  399  467
   281  638  304 -138  872  761]
 [ 556  284  232  849  -27  802  -13  -77 -121  -49  284  591  805  775
   364  748  248  264  158  371]
 [ 268  520  909  309  257  508 -189  692  648 -167  387  620  468   51
   967  753  735  -39  468  166]
 [  43  755 -193  525 -224  980 -151  327  835 -131  722   99  753  651
    28  373  -79  153  265  994]]
after sorting
[[-231 -166  -68    5   43   61   86   98  107  132  134  230  284  578
   602  730  801  834  890  995]
 [-205 -202 -191 -142 -135 -

In [9]:
#сортировка вставкой

mat = mat_gen()
print('before sorting')
print(mat)

def vstavka(mat):
    for i in range(np.ma.size(mat, 0)):
        for j in range(1, np.ma.size(mat, 1)):
            key = mat[i, j]
            k = 1
            while True:
                if k <= j and key < mat[i, j - k]:
                    key = 0
                    mat[i, j - k +1], mat[i, j - k] = mat[i, j - k], mat[i, j - k + 1]
                    key = mat[i, j - k]
                    k += 1
                else: 
                    break


print('after sorting')
vstavka(mat)
print(mat)            
    

import height or blank

import lenght or blank

import min value or blank

import max value or blank

before sorting
[[ 908  362  873  146  953   14  354  694 1013  154  620   11  986  429
   447  -13   72 -224  149 -123]
 [ -55  113  715  465  374  384  120 -227  208  323  176  -60 -176  118
   320  294  634  155  481   73]
 [ 620  589  546  167  878   72  871  249  454  368    0  670 -124  600
   776 -116  207  -60   22  105]
 [-126  158 1011  280  425  150  312  587  190  291  669  -27  266  360
   399   66  744  877  395  235]
 [ 370  673  663  652  544  195  442  498  438  187  790  247  852  401
   531  576  -57 1003 -212  349]
 [ 725 -128  653  878  694  416  842  677  -64  861  887 -221  -66  650
  -241  683  714  797  305  617]
 [ 163  808  987  359  199  152  833  602  -32 1005   54  116  268 -154
   732  846  765   24   56  604]]
after sorting
[[-224 -123  -13   11   14   72  146  149  154  354  362  429  447  620
   694  873  908  953  986 1013]
 [-227 -176  -60  -55   73  

In [10]:
#сортировка обменом

mat = mat_gen()
print('before sorting')
print(mat)

def obmen(mat):
    for i in range(np.ma.size(mat, 0)):
        while True:
            count = 0
            for j in range(0, np.ma.size(mat, 1)-1):
                if mat[i, j+1] < mat[i, j]:
                    mat[i, j+1], mat[i, j] =mat[i, j], mat[i, j+1]
                    count += 1 
            if count == 0:
                break
                


print('after sorting')
obmen(mat)
print(mat)

import height or blank

import lenght or blank

import min value or blank

import max value or blank

before sorting
[[ 960  638  799  222  -68   10   42  692 -184  655    2   76  260 -131
   461   85 -170  851  179 -122]
 [ 753 -235  597  788  878  511  229 -248  -17  356   41  885  -66  730
  -219 -221  876 -207  511  450]
 [-212   19  885  813  614  -24  980  907  864  323 -142  214  859  297
   410  569  422  953    0  760]
 [ 385  693  256  368 -129  124  273  402  776   59  188  843 -137  297
   446  994  805  688  384   34]
 [ 154  598  199  548  501  990  133  312  644  177  522  872  220  -60
  -167  657  511 -170  556  361]
 [ 697  156  631  -20   81  641 -188  914  437 -171  298  891  630  658
   908  269  992  491  394  607]
 [-153  -64  671  672  593  198  -35  892   47  669  504  372 -216  972
   389  643  -26  814  800 -217]]
after sorting
[[-184 -170 -131 -122  -68    2   10   42   76   85  179  222  260  461
   638  655  692  799  851  960]
 [-248 -235 -221 -219 -207  

In [11]:
#сортировка Шелла

print('before sorting')
print(mat)
mat = mat_gen()

def schell(mat):
    sort_sequence = [1, 4, 10, 23, 57, 132]
    s = 0
    while sort_sequence[s] < np.ma.size(mat, 1):
        s += 1

    for i in range(np.ma.size(mat, 0)):

        for y in range(s, -1, -1):
            d = sort_sequence[y]

            for j in range(1, np.ma.size(mat, 1)):
                key = mat[i, j]
                k = d

                while True:
                    if k <= j and key < mat[i, j - k]:
                        key = 0
                        mat[i, j - k +1], mat[i, j - k] = mat[i, j - k], mat[i, j - k + 1]
                        key = mat[i, j - k]
                        k += 1
                    else: 
                        break
    
    
    
    
print('after sorting')
schell(mat)
print(mat)


before sorting
[[-184 -170 -131 -122  -68    2   10   42   76   85  179  222  260  461
   638  655  692  799  851  960]
 [-248 -235 -221 -219 -207  -66  -17   41  229  356  450  511  511  597
   730  753  788  876  878  885]
 [-212 -142  -24    0   19  214  297  323  410  422  569  614  760  813
   859  864  885  907  953  980]
 [-137 -129   34   59  124  188  256  273  297  368  384  385  402  446
   688  693  776  805  843  994]
 [-170 -167  -60  133  154  177  199  220  312  361  501  511  522  548
   556  598  644  657  872  990]
 [-188 -171  -20   81  156  269  298  394  437  491  607  630  631  641
   658  697  891  908  914  992]
 [-217 -216 -153  -64  -35  -26   47  198  372  389  504  593  643  669
   671  672  800  814  892  972]]
import height or blank

import lenght or blank

import min value or blank

import max value or blank

after sorting
[[-211 -186 -133 -107  -82  -64   43  213  215  342  439  509  631  691
   695  701  821  860  887  956]
 [-188 -106  -45    3   75  

In [13]:
#турнирная

mat = mat_gen()
print('before sorting')
print(mat)

queue_lenght = 16

def tournament(arr):
    a = [i for i in arr]
    if len(a) <= queue_lenght:
        return np.array(small_tournament(a))
    else:
        return np.array(bracketsize(a))

def bracketsize(a):
    lenght = len(a)
    queue = []
    winners = []
    losers = []
    
    for i in range(lenght):
        queue.append(a[i])
        a.pop(i)
        
    while len(a) > 0:
        if not winners:
            winners.append(queue[0])
            queue.pop(0)
            
        if a[0] > winners[len(winners)]:
            queue.append(a[0])
            a.pop(0)
        else:
            losers.append(a[0])
            a.pop(0)
        
        if queue:
            winners.append(queue[0])
            queue.pop(0)
            
    while queue:
        winners.append(queue[0])
        queue.pop(0)
    if not losers:
        return winners
    else:
        a = losers + winners
        while len(a) > lenght:
            a.pop()
        bracketsize(a)
    
def small_tournament(a):
    arr = np.sort(np.array(a))
    a = [i for i in arr]


    
def tournament_2d(mat):
    for i in range(np.ma.size(mat, 0)):
        tournament(mat[i, :])
        
tournament_2d(mat)
print('after sorting')
print(mat)

import height or blank

import lenght or blank

import min value or blank

import max value or blank

before sorting
[[  49  640  503  725  786  349  540  719  371  -58  178  -76  261  449
   546  138  971   23 -134  664]
 [ -73  757  512  -60  194   19  578  182  107  824 -117  387  677  -12
   298  976  978  307  512  975]
 [-116  508  -23  154  653  131    7  256  781  634    4  786  618 1009
   267  254  491  920  832  349]
 [ 713  745  382  371  981  843  629  597  394  592  540  246  988  -77
  -203 -137 1005  635  244  986]
 [ 820  495  227  172  -80  829 -146  518 -108  -56  979  535  808  256
   794 -220 -237  947  166  962]
 [-143  849  364  154  190  576  433  629  -66 -114 -156 1009   37  662
  -100  -21  688   18  249 -132]
 [ 725  -66  468  -66  421  362  -20  296  231  728  394  271 -135  149
  -168   66   -5  752  454  154]]


IndexError: list index out of range

In [14]:
#быстрая

mat = mat_gen()
print('before sorting')
print(mat)

def quick(mat):
    def quicksort(a):
        l_a = len(a)
        if len(np.unique(a)) > 1:
            root = a[np.random.randint(0, l_a)]
            b = np.ones(len(a))
            for i in range(len(a)):
                if a[i] < root:
                    b[i] = -1
                elif a[i] == root:
                    b[i] == 0
            c_l = []
            c_e = []
            c_g = []
            for i in range(len(a)):
                if not b[i]:
                    c_e.append(a[i])
                elif b[i] == 1:
                    c_g.append(a[i])
                else:
                    c_l.append(a[i])
            c_1 = np.array(c_l)
            c_2 = np.array(c_e)
            c_3 = np.array(c_g)
            return np.concatenate((quicksort(c_1),  quicksort(c_2), quicksort(c_3)))
        else:
            return(a)


    for i in range(np.ma.size(mat, 0)):
        mat[i, :] = quicksort(mat[i, :])


print('after sorting')
quick(mat)
print(mat)



import height or blank

import lenght or blank

import min value or blank

import max value or blank

before sorting
[[ 764  648  608  854  287 -182  368  804  502  -69   39  820  221 1011
   397  747 -107  574 -221  582]
 [ 733   -6  262  315  282  447  449  124  149  260  410  442   46  382
  -212  550  656  794  196  463]
 [ 454  -25  769  515  719  816 -249 -207  -81  728 -136  -46    4  895
    18   67  -32  295  393  -32]
 [-156  388 -215  587  186 -235  838  186  460  661  609  411  551 -123
   679  629  448  173  396  852]
 [ 972  818  355   31 -129  946  741 -142  710  346  346  251  792  784
   150  617  309  958  333 -149]
 [ 646  449  165 -223  550  833  939 1012    8  -48  493  736  351  198
   899  369  476  111  334  308]
 [  20  842  484  557  -40  -85  -50  820  159  353  187  195  517  943
   911 -108  579  748  183  607]]
after sorting
[[-221 -182 -107  -69   39  221  287  368  397  502  574  582  608  648
   747  764  804  820  854 1011]
 [-212   -6   46  124  149  

In [15]:
#пирамидальная

mat = mat_gen()
print('before sorting')
print(mat)

def heapsort(mat):
    def heapify(a, lenght, i):
        root_index = i
        left_index = 2*root_index + 1
        right_index = 2*root_index + 2

        if left_index < lenght and a[root_index] < a[left_index]:
            root_index = left_index

        if right_index < lenght and a[root_index] < a[right_index]:
            root_index = right_index

        if root_index != i:
            a[i], a[root_index] = a[root_index], a[i]

            heapify(a, lenght, root_index)


    def pyrsort(a):
        n = len(a)

        for i in range(n//2 - 1 , -1, -1):
            heapify(a, n, i)

        for i in range(n - 1, 0, -1):
            a[i], a[0] = a[0], a[i]
            heapify(a, i, 0)


    for i in range(np.ma.size(mat, 0)):
        pyrsort(mat[i, :])

print('after sorting')
heapsort(mat)
print(mat)

import height or blank

import lenght or blank

import min value or blank

import max value or blank

before sorting
[[ 330  615  538   48  117  -57  431  638  771  673  874  -80 -155    4
   472  256  233  855  408 -183]
 [ 925 -231  255   77  442  873  277  625   22  537  492  174 -210  700
    -7  853  941  132  851 -221]
 [ 631   71  662 -123  693  768  257  940  349  774 -171 -119  395 -198
   311 -133  923  229  324  -35]
 [ 796  377  257  515  445  382  446  232  493   44  424  271  182   23
   644 -153  907  233  922  301]
 [ 432  295  380   53   39 -107  556 -106 -166  177   72  125  689  821
   155  987  441   39  983 -250]
 [-140   15  441  244  -84  760  218  445  -58 -115  224  936  787 -170
   286  458 -228  342  249  423]
 [ 288  868  626  107  529   30 -172  178  634  208  720  614 -107  488
   395  471  224   81 -181 -217]]
after sorting
[[-183 -155  -80  -57    4   48  117  233  256  330  408  431  472  538
   615  638  673  771  855  874]
 [-231 -221 -210   -7   22  

In [18]:
#у меня так и не олучилось реализовать сортировку турниром

import numpy as np
import time as ti

mat = mat_gen()

mat1 = mat
mat2 = mat
mat3 = mat
mat4 = mat
mat5 = mat
mat6 = mat

t0= ti.clock()
vblbor(mat1)
t1 = ti.clock() - t0
print("Time vblbor: ", t1)

t0= ti.clock()
vstavka(mat2)
t1 = ti.clock() - t0
print("Time vstavka: ", t1)

t0= ti.clock()
obmen(mat3)
t1 = ti.clock() - t0
print("Time obmen: ", t1)

t0= ti.clock()
schell(mat4)
t1 = ti.clock() - t0
print("Time schelle: ", t1)

t0= ti.clock()
quick(mat5)
t1 = ti.clock() - t0
print("Time quicksort: ", t1)

t0= ti.clock()
heapsort(mat6)
t1 = ti.clock() - t0
print("Time heapsort: ", t1)

import height or blank

import lenght or blank

import min value or blank

import max value or blank



C:\Users\lulxd\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  from ipykernel import kernelapp as app
C:\Users\lulxd\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
C:\Users\lulxd\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
C:\Users\lulxd\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
C:\Users\lulxd\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: De

Time vblbor:  0.04717810000056488
Time vstavka:  0.0026066999998874962
Time obmen:  0.002640100000462553
Time schelle:  0.009167199999865261
Time quicksort:  0.38124359999983426
Time heapsort:  0.03433200000017678


C:\Users\lulxd\Anaconda3\lib\site-packages\ipykernel_launcher.py:37: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
C:\Users\lulxd\Anaconda3\lib\site-packages\ipykernel_launcher.py:40: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
C:\Users\lulxd\Anaconda3\lib\site-packages\ipykernel_launcher.py:42: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
