In [23]:
import numpy as np

mat = np.random.randint(0, 4, (4, 4))
print('original matrix')
print(mat)

def proj(mat, axis='xy'):
    proj_mat = np.zeros((np.ma.size(mat, 0), np.ma.size(mat, 1)))
    if axis == 'xy':
        for i in range(np.ma.size(mat, 0)):
            for j in range(np.ma.size(mat, 1)):
                if mat[i, j]:
                    proj_mat[i, j] = 1
        return proj_mat
    
    elif axis == 'zx':
        for i in range(np.ma.size(mat, 0)):
            temp = 0
            for j in range(np.ma.size(mat, 1)):
                if mat[j, i] > temp:
                    temp = mat[j, i]
            for j in range(temp):
                proj_mat[np.ma.size(mat, 1) - j - 1, np.ma.size(mat, 0) - i - 1] = 1
        return proj_mat
    
    elif axis == 'yz':
        for i in range(np.ma.size(mat, 0)):
            temp = 0
            for j in range(np.ma.size(mat, 1)):
                if mat[i, j] > temp:
                    temp = mat[i, j]
            for j in range(temp):
                proj_mat[np.ma.size(mat, 1) - j - 1, np.ma.size(mat, 0) - i - 1] = 1
        return proj_mat
    
    else:
        return 'incorrect axis label!'


def surface(mat):
    return np.sum(proj(mat)) + np.sum(proj(mat, 'yz')) + np.sum(proj(mat, 'zx'))

print('________')
print('summary surface = ',  surface(mat))
print('________')
print('xy view')
print(proj(mat))   
print('________')
print('yz view')
print(proj(mat, 'yz'))
print('________')
print('zx view')
print(proj(mat, 'zx'))


original matrix
[[3 1 3 1]
 [3 3 2 1]
 [3 3 3 1]
 [2 1 1 3]]
________
summary surface =  40.0
________
xy view
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
________
yz view
[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
________
zx view
[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
